language: c

os: linux
dist: trusty
sudo: required

# cache dependencies build so they don't have to be built every time
cache:
      directories:
        - ${TRAVIS_BUILD_DIR}/.local

matrix:
      include:
        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
                - gfortran-7
                - libhwloc-dev
                - libiomp-dev
                - libnuma-dev
                - libpfm4
                - libpfm4-dev
                - llvm-3.9-dev
                - numactl
                - wget
          env:
             - C_COMPILER="gcc-7"
             - CXX_COMPILER="g++-7"
             - FORTRAN_COMPILER="gfortran-7"

        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-8
                - gfortran-8
                - libhwloc-dev
                - libiomp-dev
                - libnuma-dev
                - libpfm4
                - libpfm4-dev
                - llvm-3.9-dev
                - numactl
                - wget
          env:
             - C_COMPILER="gcc-8"
             - CXX_COMPILER="g++-8"
             - FORTRAN_COMPILER="gfortran-8"

before_install:
    - export CC="${C_COMPILER}"
    - export CXX="${CXX_COMPILER}"
    - export FC="${FORTRAN_COMPILER}"

install:
    - export SWHOME="${TRAVIS_BUILD_DIR}/.local"

    # Install the dependencies into SWHOME
    - travis_wait 50 ./install_deps.sh --jemalloc --mpi --build_dir $(pwd) --install_dir ${SWHOME}

    - export JEPATH="${SWHOME}/jemalloc"
    - export MPI_PATH="${SWHOME}/openmpi-3.1.1"
    - export LD_LIBRARY_PATH=${JEPATH}:${LD_LIBRARY_PATH}
    - export PKG_CONFIG_PATH=${JEPATH}:${PKG_CONFIG_PATH}
    - export PATH=${MPI_PATH}/bin:$PATH

script:
    - export SICM_ROOT=${SWHOME}/SICM

    # build SICM
    - ./autogen.sh
    - mkdir -p build
    - cd build
    - ../configure --with-jemalloc=${JEPATH} --prefix=${SICM_ROOT}
    - make -j $(nproc --all)
    - make install
    - ls -R
    - cp src/low/sicm_f90.mod ${SICM_ROOT}/lib
    - export LD_LIBRARY_PATH=${SICM_ROOT}/lib:${LD_LIBRARY_PATH}

    - cd ..

    - numactl --hardware

    # build and run tests
    - SICM_ROOT=${SICM_ROOT} make -C test
    - find test -type f -executable -exec echo "Running {}" \; -exec {} \;

    # run SNAP with SICM
    - cd examples/SNAP/src
    - CC=${MPI_PATH}/bin/mpicc CXX=${MPI_PATH}/bin/mpic++ FC=${MPI_PATH}/bin/mpif90 MPI_INCLUDE=${MPI_PATH}/include OMPI_FC=${FORTRAN_COMPILER} SICM_ROOT=${SICM_ROOT} make -j $(nproc --all)
    - for input in ../qasnap/mms_src/1d_fixup_*.inp;  do mpirun -np 1 --oversubscribe ./gsnap $input /dev/null; done
    # - for input in ../qasnap/mms_src/2d_fixup_*.inp;  do mpirun -np 4 --oversubscribe ./gsnap $input /dev/null; done
    # - for input in ../qasnap/mms_src/3d_fixup_t*.inp; do mpirun -np 8 --oversubscribe ./gsnap $input /dev/null; done
    # - mpirun -np 4 --oversubscribe ./gsnap ../qasnap/mms_src/3d_fixup_st.inp /dev/null
