language: c

os: linux
dist: trusty
sudo: required

matrix:
      include:
        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
                - gfortran-7
                - numactl
                - libnuma-dev
                - wget
          env:
             - C_COMPILER="gcc-7"
             - CXX_COMPILER="g++-7"
             - FORTRAN_COMPILER="gfortran-7"

        - addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-8
                - gfortran-8
                - numactl
                - libnuma-dev
                - wget
          env:
             - C_COMPILER="gcc-8"
             - CXX_COMPILER="g++-8"
             - FORTRAN_COMPILER="gfortran-8"

before_install:
    - export CC="${C_COMPILER}"
    - export CXX="${CXX_COMPILER}"
    - export FC="${FORTRAN_COMPILER}"

install:
    # install jemalloc
    - git clone https://github.com/jemalloc/jemalloc.git
    - cd jemalloc
    - ./autogen.sh
    - mkdir build
    - cd build
    - export JEPATH=$(pwd)
    - ../configure --prefix=${JEPATH} --with-jemalloc-prefix=je_
    - make -j $(nproc --all)
    - make -j $(nproc --all) -i install
    - cd ${TRAVIS_BUILD_DIR}

    # install openmpi manually
    - wget https://download.open-mpi.org/release/open-mpi/v3.1/openmpi-3.1.1.tar.bz2
    - tar -xf openmpi-3.1.1.tar.bz2
    - cd openmpi-3.1.1
    - mkdir build && cd build
    - export MPI_PATH=$(pwd)
    - travis_wait ../configure --prefix=${MPI_PATH} --without-verbs --without-fca --without-mxm --without-ucx --without-portals4 --without-psm --without-psm2 --without-libfabric --without-usnic --without-udreg --without-ugni --without-xpmem --without-alps --without-sge --without-tm --without-lsf --without-slurm --without-pvfs2 --without-plfs --without-cuda --disable-oshmem --enable-mpi-fortran --disable-oshmem-fortran --disable-libompitrace --disable-io-romio --disable-static &> /dev/null
    - travis_wait make -j $(nproc --all) &> /dev/null
    - travis_wait make -j $(nproc --all) install &> /dev/null
    - cd ${TRAVIS_BUILD_DIR}

script:
    # build SICM
    - make -j $(nproc --all)
    - export SICM_ROOT=$(pwd)
    - export LD_LIBRARY_PATH=${SICM_ROOT}:${JEPATH}/lib:${MPI_PATH}/lib:$LD_LIBRARY_PATH
    - export PATH=${MPI_PATH}/bin:$PATH

    # build tests
    - make -C test
    - numactl --hardware

    # run tests
    - find test -type f -executable -exec echo "Running {}" \; -exec {} \;

    # run SNAP with SICM
    - cd examples/SNAP/src
    - CC=${MPI_PATH}/bin/mpicc CXX=${MPI_PATH}/bin/mpic++ FC=${MPI_PATH}/bin/mpif90 MPI_INCLUDE=${MPI_PATH}/include OMPI_FC=${FORTRAN_COMPILER} make -j $(nproc --all)
    - for input in ../qasnap/mms_src/1d_fixup_*.inp;  do mpirun -np 1 --oversubscribe ./gsnap $input /dev/null; done
    # - for input in ../qasnap/mms_src/2d_fixup_*.inp;  do mpirun -np 4 --oversubscribe ./gsnap $input /dev/null; done
    # - for input in ../qasnap/mms_src/3d_fixup_t*.inp; do mpirun -np 8 --oversubscribe ./gsnap $input /dev/null; done
    # - mpirun -np 4 --oversubscribe ./gsnap ../qasnap/mms_src/3d_fixup_st.inp /dev/null
